version: '3.8'
services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: edu-platform-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: edu-platform
    volumes:
      - mongo-data:/data/db



  # Backend API
  backend:
    build: ./backend
    container_name: edu-platform-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password@mongo:27017/edu-platform?authSource=admin
      - AUTH0_DOMAIN=your-domain.auth0.com
      - AUTH0_CLIENT_ID=your-client-id
      - AUTH0_CLIENT_SECRET=your-client-secret
      - AUTH0_AUDIENCE=https://your-api.com
      - AUTH0_ISSUER=https://your-domain.auth0.com/
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
      - minio

  # Frontend
  frontend:
    build: ./frontend
    container_name: edu-platform-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_AUTH0_DOMAIN=your-domain.auth0.com
      - VITE_AUTH0_CLIENT_ID=your-client-id
      - VITE_BACKEND_URL=http://localhost:5000/api
    depends_on:
      - backend

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: edu-platform-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:latest
    container_name: edu-platform-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
  minio-data:
